### ISSUE TITLE
Adding a Peer-to-Peer (P2P) support

### ISSUE THREAD

**Issue by ohault** [openvstorage/arakoon#157]
Connectivity between nodes could also support a mode of communication based on P2P to provide automatic NAT traversal. This will be an alternative to current layer 3 connectivity requirement of Arakoon and it will open a completely new window of opportunities for Arakoon cluster.

**Comment by wimpers** [comment]
There are no plans for P2P support for Arakoon or Open vStorage.

**Comment by ohault** [comment]
I can understand this is somehow a paradigm shift, but for a storage solution it's also strategic to stay aligned, from an architectural point of view, with network evolution (Zero Trust Network, multi-pathing, P2P, ...). Leveraging end-to-end connectivity would be a deep innovation for Arakoon and Open vStorage. If too early for a short term roadmap, can you please consider to keep this point a longer term roadmap? My 2 cents.
