### ISSUE TITLE
What if the head.db is not the correct one?

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/arakoon#161]
What happens if we copy the main.db to a tlog directory from another cluster?
If this cluster needs to copy the head.db to the main.db will this trigger an exception in the Arakoon or not?
I know there is a function in Arakoon (--copy-db-to-head) to prevent this.

Please make sure we cannot start the Arakoon with another head.db from another cluster.

**Comment by domsj** [comment]
fixed by #170
