### ISSUE TITLE
copy-db-to-head not working as expected

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/arakoon#168]
I'm creating this ticket for tracking purpose as Romain should already be aware of this. We noticed that the --copy-db-to-head functionality of arakoon isn't working. We can work around this manually, but a working feature would be nice to have as regular collapsing is taking too long on OVH and we're trying to keep up manually to not have the disk run full.

As far as I remember, the running arakoon process doesn't seem to start the copy process. Romain should have more details.

**Comment by domsj** [comment]
Can you try running this with debug logging enabled?

**Comment by jtorreke** [comment]
Attached is the debug log file. My connection is incoming at:

Apr 19 18:15:14 ovs01 arakoon[63013]: 2017-04-19 18:15:14 292155 +0200 - ovs01 - 63013/0000 - arakoon - 301 - info - 172.20.20.1:client_service:session=0 connection=172.20.20.1:client_service_1 socket_address=ADDR_INET 172.20.20.1,51532

And disconnected at:

Apr 19 18:17:01 ovs01 arakoon[63013]: 2017-04-19 18:17:01 751546 +0200 - ovs01 - 63013/0000 - arakoon - 4850 - info - exiting session (0) connection=172.20.20.1:client_service_1: End_of_file; backtrace:; Raised at file "map.ml", line 122, characters 16-25; Called from file "src/core/lwt.ml", line 161, characters 4-40
Apr 19 18:17:01 ovs01 arakoon[63013]: 2017-04-19 18:17:01 751573 +0200 - ovs01 - 63013/0000 - arakoon - 4851 - info - 172.20.20.1:client_service_1: closing

[arakoon-copy-db-debug.txt](https://github.com/openvstorage/arakoon/files/936000/arakoon-copy-db-debug.txt)

**Comment by toolslive** [comment]
#171
