### ISSUE TITLE
Arakoon cluster status

### ISSUE THREAD

**Issue by wimpers** [openvstorage/arakoon#177]
Arakoon should expose call to request the status of the Arakoon cluster (f.e 2/3 nodes are working fine so the healthcheck can query this status. (see https://github.com/openvstorage/openvstorage-health-check/issues/324)

**Comment by toolslive** [comment]
something like:
```
$ arakoon --statistics -config /home/romain/workspace/tmp/arakoon/abm.ini | grep node_is
node_is: (abm_1,5142)(abm_2,5142)(abm_0,5142)}
```
shows the master's view on the cluster, which is basically a counter for each node. That counter is the last acknowledged update for that node. 
If there's a node for which the counter is significantly lower than the master's counter, that node is lagging which means: isolated, offline or just too slow. 

This call is also available for the python/ocaml clients
