### ISSUE TITLE
Change copy-head-to-db CLI signature to use -config

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/arakoon#179]
Currently most arakoon CLI commands accept a -config parameter to point to the config of the cluster, except for copy-head-to-db. This one accepts a clustername, IP, port and the number of tlog files to leave untouched. Can we make CLI arguments uniform so a --collapse-local and --copy-db-to-head accept the same arguments as the result of both actions is the same?

  --copy-db-to-head <cluster_id> <ip> <port> <tlogs_to_keep> requests the node to copy its database to the head location, after which it will remove old tlogs
  --collapse-local <node_id> <n> collapse all but <n> tlogs into the head database

**Comment by toolslive** [comment]
what with backwards compatibility and existing scripts?

**Comment by jtorreke** [comment]
Afaik only 2 'scripts' use this functionality:
* the framework for internally managed arakoons
* the ops scripts for externally managed arakoons

The latter I can manage. The first one is probably a small fix as they have all needed info anyway.
Maybe it would be a good plan to review other commands as well and straighten things out while we're at it.

**Comment by toolslive** [comment]
To make discussion easier: These following have similar signatures.
`--collapse-remote <cluster_id> <ip> <port> <n>`
`--copy-db-to-head <cluster_id> <ip> <port> <n>` 

`--collapse-local <node_id> <n>` needs `-config` as that's the easiest way to provide all the paths you need.
