### ISSUE TITLE
Output when using collapse-local or copy-db-to-head is stderr instead of stdout

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/arakoon#180]
As the ticket says, output of these commands (probably others as well) is logged in stderr instead of stdout.  Can this be changed to stdout for regular logging?

Thanks!

**Comment by wimpers** [comment]
@domsj  @toolslive we assumed this is a small one?

**Comment by toolslive** [comment]
Currently for these commands, logging goes to `stderr` while regular output (if any) goes to `stdout`.
So you want logging to go to `stdout`. Fine, but then where do you want regular output to end up ?

**Comment by wimpers** [comment]
Closing this down as we are moving to RocksDB instead of Tokyocabinet? This means collapse and copy-db-to-head will be removed. Re-open if really needed.
