### ISSUE TITLE
High memory usage on ABM

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/arakoon#182]
The memory usage of an ABM on the Nuvolat setup was 57GB high.

arakoon version: 1.9.18
alba version: ee-1.5.2

```
22036 ovs       20   0 57.173g 0.054t   9092 S  15.6 29.5   2322:12 /usr/bin/arakoon --node N0RCG4vXgbP0w8LQ -config arakoon://config/ovs/arakoon/ny1-ssdbackend01-abm/config?ini=%2Fmnt%2Fssd1%2Farakoon%2Fexternal_arakoon_cacc.ini -autof+
```

We see a lot of assert failed attempts on this particular node/abm. (not sure if this is caused by the already fixed bug on https://github.com/openvstorage/alba_ee/issues/52) (same abm)

```
Albamgr: Assert failed /alba/ns/list/c220cf34-f904-4fff-82bc-16271219e457_bc_000000086 (attempt 4)
```

**Comment by domsj** [comment]
This could indeed be related to the linked ticket.
The maintenance processes will keep on trying to mark an osd as claimed by this backend, but that will unfortunately keep on failing.
So this results in wasted cpu cycles and some wasted memory usage, unfortunately I don't immediately see how it would explain 50+ GB of ram usage.

For now I recommend periodically restarting the affected processes.

On a slightly longer timescale I suggest that @openvstorage/qa validates that alba-ee 1.5.3 or 1.5.4 is good enough to be deployed on this env to see if it makes the problem go away.

**Comment by wimpers** [comment]
@jeroenmaelbrancke can we consistently reproduce this behavior (same node? other nodes)?

If so, @domsj  would it make sense to update on that node the component(s) (which?) to see if this solves the issue?

**Comment by toolslive** [comment]
not an arakoon issue (but a plugin issue)

**Comment by jeroenmaelbrancke** [comment]
So far we do not have this issue with alba plugin: 1.5.28
