### ISSUE TITLE
Allow keys to be excluded in prefix_entries and range_entries

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/arakoon#205]
### Feature description
Having some filtering when dealing with a list of keys could be handy for some optimization

**Comment by wimpers** [comment]
You probably have a certain use case in mind (filter)? Could you give an example?

**Comment by JeffreyDevloo** [comment]
I had a valid usecase but I was able to solve it with a multi-key fetch instead.
The use-case was: suppose you know a few items not to be included in a certain range (vdisklist for example, you know the key of vdisk1 which you don't want to fetch). You can do a prefix_entries and then delete the key of vdisk1 or the server could do it for you (less data transmitted, less cpu cycles for the client)

**Comment by toolslive** [comment]
So to exclude the key being sent from the server to the client, you need to send it to the server first.
No win there.
