### ISSUE TITLE
Use the standard ovs log format (timestamp)

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/arakoon#80]
Can you please use the standard ovs log format described on the [gitbook](https://openvstorage.gitbooks.io/framework/content/docs/log.html).

Only the timestamp isn't correct.

```
2016/06/06 06:57:27 588953 +0200 - cmp01 - 12197/0 - arakoon - 15593 - info - iuMMCJanEt6V2jUJ is master
```

should be

```
2016-06-06 06:57:27 588953 +0200 - cmp01 - 12197/0 - arakoon - 15593 - info - iuMMCJanEt6V2jUJ is master
```

Also Alba needs this modification.

**Comment by toolslive** [comment]
#81
