### ISSUE TITLE
Arakoon cluster has no master when rebuilding a arakoon.

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/arakoon#93]
We had a broken arakoon on node A. But B & C were still active and had an active master.
When rebuilding node A, we saw that the cluster suddenly had no master.

**Comment by wimpers** [comment]
@kinvaris can you please add logs? Env id? Based upon this ticket detail we can't do much.

**Comment by kinvaris** [comment]
@wimpers: No logs are required for this because they are no usable logs are produced. You can easily reproduce it:

```
1. Startup 3 node arakoons
2. Put alot of data in it
3. Stop 1 node
4. Check master
5. wipe node 1
6. start node 1 (rebuild starts)
7. Check master (lost master here)
```

**Comment by wimpers** [comment]
Is step 3 stop node 1 or stop a node of the cluster?  If you have 3 nodes and  stop a node (step 3) and you wipe node 1 , you lost 2 out of the 3 nodes. In that case it is normal there is no master.

**Comment by kinvaris** [comment]
The node in question to be stopped, wiped and started is node X, but it has to be the same node. You can apply it to any node.

**Comment by wimpers** [comment]
@toolslive @domsj are you aware of this issue?

**Comment by domsj** [comment]
yes, @toolslive tried to reproduce it today without success.

**Comment by toolslive** [comment]
@kinvaris how much is "alot" ?

**Comment by kinvaris** [comment]
This was observed on a environment with a small tlog/tlx size. In this situation the arakoon had 150K uncollapsed tlog/tlx files.

**Comment by toolslive** [comment]
sorry, cannot reproduce. If it happens again, please reopen.
