### ISSUE TITLE
Observed a potentially corrupt tlx file causing restart loop of arakoon process

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/arakoon#94]
Tlx file appears to be at least one week old, indicating arakoon collapse probably not running (failing)

@domsj: pls complete with relevant details to further investigate this issue.

Also document workaround applied

**Comment by domsj** [comment]
```
2016-07-04 11:12:39 699822 +0200 - e190-1 - 59258/0 - arakoon - 2255 - info - Completed replay of 62011.tlx, took 0.062215 seconds, 6877 to go
2016-07-04 11:12:39 699929 +0200 - e190-1 - 59258/0 - arakoon - 2256 - info - Replaying tlog file: 62012.tlx (1102/7978)
2016-07-04 11:12:39 740984 +0200 - e190-1 - 59258/0 - arakoon - 2257 - fatal - going down: (Failure "update 63457065, store @ 63457063 don't fit"); backtrace:; Raised at file "map.ml", line 117, characters
 16-25; Called from file "src/core/lwt.ml", line 161, characters 4-40
2016-07-04 11:12:39 741008 +0200 - e190-1 - 59258/0 - arakoon - 2258 - fatal - after pick
2016-07-04 11:12:39 743067 +0200 - e190-1 - 59258/0 - arakoon - 2259 - info - Crash log dumped
```

The above shows there might be a problem in 62012.tlx.
Dumping the tlogs shows:

```
63457063:(Vc
7810759283706196847:(Vc
63457065:(Vc
```

So for some reason the 'i' of one entry got corrupted.
While hex editing the (uncompressed) tlog (to manually work around the problem) I noticed that the wrong value matches the ascii text `osds/del` which happens to be a string that is present many times in the tlog (which made it a bit harder to find the exact bytes to change!).
The bytes I had to edit started at offset 3719946, which isn't even a multiple of 4, which to me is an indication this is probably not a hardware problem but instead a bug in arakoon?
Also it's the second time we've seen this.

(For future readers encountering the same problem: 'i' values are serialized in little endian format. You could use 'bvi' to do the editing.)

**Comment by wimpers** [comment]
We need a workaround for OPS for this.

**Comment by wimpers** [comment]
How many times did we see this issue in the field?

**Comment by wimpers** [comment]
@domsj , @toolslive , please document the workaround for OPS

**Comment by domsj** [comment]
I think we've seen this 3 times in total.
Twice by @jtorreke, and once elsewhere.

Procedure for ops could be either:
- uncompress tlx to tlog, find the offending bytes and fix them (this step can be a bit tricky), restart node
- or in case of a still running cluster just throw state of this node away and let it catch up from the others

**Comment by wimpers** [comment]
BAM decided not to fix. If someone disagrees, please talk to @saelbrec  or me.
